#!/bin/sh
#
# wildefyr - 2016 (c) MIT
# set current background and includes logic to blur background

ARGS="$@"

usage() {
    cat >&2 << EOF
Usage: $(basename $0) [blur integer]
EOF

    test $# -eq 0 || exit $1
}

main() {
    . fyrerc

    # check for dups
    test -z "$BACK" && return 0
    test -z "$WALL" && return 0
    test -e "$WALL" || return 1

    test $(lsw | wc -l) -eq 0 && {
        BLUR=0
    } || {
        test $# -eq 0 || {
            intCheck $1
            BLUR=$1
        }
    }

    # finally: set our wall
    printf '%s\n' "$BACK" | grep -q "hsetroot" && {
        $BACK -blur $BLUR
    } || {
        $BACK
    }
}

for arg in $ARGS; do
    case "$arg" in
        -q|--quiet)       QUIETFLAG=true ;;
        h|help|-h|--help) usage 0        ;;
    esac
done

test "$QUIETFLAG" = "true" && {
    main $ARGS 2>&1 > /dev/null
} || {
    main $ARGS
}
