#!/bin/sh
#
# wildefyr - 2016 (c) MIT
# set current background and includes logic to blur background

ARGS="$@"

usage() {
    cat >&2 << EOF
Usage: $(basename $0) [blur integer]
EOF

    test $# -eq 0 || exit $1
}

main() {
    . fyrerc

    # if we don't have a wall, don't do anything
    test -z "$WALL" && return 0
    test -e "$WALL" || return 1

    test $# -eq 0 && BLUR=0 || intCheck $1
    test $(lsw | wc -l) -eq 0 && BLUR=0

    # finally: set our wall
    $BACK
}

for arg in $ARGS; do
    case "$arg" in
        -q|--quiet)       QUIETFLAG=true ;;
        h|help|-h|--help) usage 0        ;;
    esac
done

test "$QUIETFLAG" = "true" && {
    main $ARGS 2>&1 > /dev/null
} || {
    main $ARGS
}
