#!/bin/sh
#
# wildefyr - 2016 (c) MIT
# blur current background

ARGS="$@"

usage() {
    cat >&2 << EOF
Usage: $(basename $0) [blur integer]
EOF

    test $# -eq 0 || exit $1
}

main() {
    . fyrerc

    test $# -eq 0 && usage 1 || intCheck $1

    test $(lsw | wc -l) -eq 0 && BLUR=0
    test ! -z "$WALL" && $WALL -blur ${1:-$BLUR}
}

for arg in $ARGS; do
    case "$arg" in
        -q|--quiet)       QUIETFLAG=true ;;
        h|help|-h|--help) usage 0        ;;
    esac
done

test "$QUIETFLAG" = "true" && {
    main $ARGS 2>&1 > /dev/null
} || {
    main $ARGS
}
