#!/bin/sh
#
# File        : /home/wildefyr/fyre/detection
# Maintainer  : Wildefyr | http://wildefyr.net
# Copyright   : Wildefyr | Licensed under the WTFPL license.
# Description : Find special windows and add them to an ignore list.

# I recommend if you want to have these windows in any other position or even
# added to a new group, put it under where it checks it's wid.

source fyrerc

fehCounter=0
ts3Counter=0
steamCounter=0
battlenetCounter=0

for i in $(seq $windowsOnscreen); do
    wid=$(lsw | head -n $i | tail -1)

    #mpv
    if [[ $(wclass c $wid) == "vdpau" ]]; then
        mpvWid=$wid
        mpvCounter=1
    elif [[ $(wclass c $wid) == "xv" ]]; then
        mpvWid=$wid
        mpvCounter=1
    fi

    #feh
    if [[ $(wclass c $wid) == *"feh"* ]]; then
        printf '%s\n' $wid >> $DETECT
        fehCounter=$((fehCounter + 1))
    fi

    #firefox
    if [[ $(wclass p $wid) == *"firefox"* ]]; then
        printf '%s\n' $wid >> $DETECT
        firefoxCounter=1

        if [ ! -e $GROUPSDIR/group.2 ]; then
            wgroups -s $wid 2
        fi
    fi

    #teamspeak
    if [[ $(wclass c $wid) == *"ts3"* ]]; then
        printf '%s\n' $wid >> $DETECT
        ts3Counter=$((ts3Counter + 1))

        if [ ! -e $GROUPSDIR/group.3 ]; then
            if [[ $(cat $GROUPSDIR/group.3) != $wid ]]; then
                sed -i 'd' $GROUPSDIR/group.3
                wgroups -s $wid 3
                wgroups -u 3
            fi
        fi
    fi

    #steam
    if [[ $(wclass c $wid) == "Steam" ]]; then
        printf '%s\n' $wid >> $DETECT
        steamCounter=$((steamCounter + 1))
    fi

    #blizzard
    if [[ $(wclass c $wid) == "Battle.net.exe" ]]; then
        printf '%s\n' $wid >> $DETECT
        battlenetCounter=$((battlenetCounter + 1))
    fi
    if [[ $(wclass c $wid) == "Hearthstone.exe" ]]; then
        printf '%s\n' $wid >> $DETECT
        battlenetCounter=$((battlenetCounter + 1))
    fi

    #urxvt
    if [[ $(wclass c $wid) == "urxvt" ]]; then
        printf '%s\n' $wid >> $DETECT
    fi
done

totalDetectList=$((fehCounter + mpvCounter + firefoxCounter + ts3Counter + \
                   steamCounter + battlenetCounter))

windowsOnscreen=$((windowsOnscreen - totalDetectList))
