#!/bin/sh
#
# wildefyr & z3bra - 2016 (c) wtfpl
# catch window events from wew

usage() {
    cat >&2 << EOF
Usage: $(basename $0) [-d|--debug] [-h|--help]
EOF

    test $# -eq 0 || exit $1
}

case "$1" in
    -d|--debug)
        . fyrerc

        wew | while IFS=: read -r ev wid; do

        cat << EOF
$ev $wid
    $(name $wid)
    $(wname $wid)
    $(class $wid)
    $(process $wid)
EOF
        done
        ;;
    h|help|-h|--help)
        usage 0
        ;;
esac

wew | while IFS=: read ev wid; do
    . fyrerc

    case "$ev" in
        7)
            test "$SLOPPY" = "true" && {
                wattr o "$wid" || {
                    focus "$wid" "--disable" -q
                }
            }
            ;;
        16)
            case "$WOKRFLOW" in
                "workspaces")
                    windows -q -a "$wid" "$(cat $active)"
                    ;;
                *)
                    wattr o "$wid" || winopen "$wid"
                    ;;
            esac

            blur
            ;;
        17)
            # clean hover
            hover -c "$wid"
            # clean fullscreen
            test -f "$FSFILE" && test "$(cut -d\  -f 5 < "$FSFILE")" = "$wid" && {
                rm -f "$FSFILE"
            }
            ;;
        18)
            wattr "$(pfw)" || focus prev

            blur
            ;;
        19)
            blur
            ;;
    esac
done
