#!/bin/sh
#
# wildefyr & z3bra - 2016 (c) wtfpl
# focus wrapper with fullscreen check

ARGS="$@"

usage() {
    cat >&2 << EOF
Usage: $(basename $0) <next|prev|full|wid> [disable]
    wid:     Focus the given window.
    next:    Focus the next window on the stack.
    prev:    Focus the previous window on the stack.
    full:    Focus the fullscreen window.
    disable: Disable movement of the mouse.
EOF

    test $# -eq 0 || exit $1
}

hoverPush() {
    test -f "$HOVER" && {
        while read -r line; do
            wid=$(printf '%s\n' "$line" | cut -d\  -f 1)
            chwso -r "$wid"
        done < "$HOVER"
    }
}

focusWid() {
    wattr "$1" && wid="$1"
    focusMethod
}

focusNext() {
    wid="$(lsw | grep -v "$PFW" | sed '1 p;d')"
    test ! -z "$wid" && focusMethod
}

focusPrev() {
    wid="$(lsw | grep -v "$PFW" | sed '$ p;d')"
    test ! -z "$wid" && focusMethod
}

focusFull() {
    test -f "$FSFILE" && wid="$(cut -d\  -f 5 < "$FSFILE")" || usage 1
    test ! -z "$wid" && focusMethod
}

focusMethod() {
    test "$wid" = "$(pfw)" && exit 1

    # try to be as responsive as possible to user input
    chwso -r "$wid"
    wtf "$wid"

    # focus correctly even if there is a fullscreen window
    test -f "$FSFILE" && {
        test "$(cut -d\  -f 5 "$FSFILE")" = "$wid" && {
            setborder none "$wid"
        } || {
            test "$(cut -d\  -f 5 "$FSFILE")" = "$PFW" && {
                setborder active "$wid"
                setborder none "$PFW"
            }
        }
    } || {
        test "$wid" != "$PFW" && {
            setborder active "$wid"
            setborder inactive "$PFW"
        }
    }
}

moveMouse() {
    . mouse

    mouseStatus=$(getMouseStatus)
    test $mouseStatus -eq 1 && moveMouseEnabled "$wid"
}

main() {
    . fyrerc

    # automatically focus the window underneath the cursor
    test $# -eq 0 && {
        wid=$(underneath)
        test ! -z "$wid" && focusMethod
    } || {
        case "$1" in
            "next") focusNext     ;;
            "prev") focusPrev     ;;
            "full") focusFull     ;;
            0x*)    focusWid "$1" ;;
            *)      usage 1       ;;
        esac

        case "$2" in
            "--enable")  MOUSE=true  ;;
            "--disable") MOUSE=false ;;
        esac

        test "$MOUSE" = "true" && moveMouse
    }

    hoverPush
}

for arg in $ARGS; do
    case "$arg" in
        -q|--quiet)       QUIETFLAG=true ;;
        h|help|-h|--help) usage 0        ;;
    esac
done

test "$QUIETFLAG" = "true" && {
    main $ARGS 2>&1 > /dev/null
} || {
    main $ARGS
}
