#!/bin/sh
#
# File            : /home/wildefyr/fyre/fullscreen
# Maintainer      : Wildefyr | http://wildefyr.net
# Copyright       : Wildefyr | Licensed under the WTFPL license.
# Depends on      : wmutils
# Original Author : z3bra
# Description     : Toggle fullscreen states, between none, gaps and full.

source fyrerc

usage() {
    echo "Usage: $(basename $0) [wid]"
    exit 1
}

if [ -e $FULLSCRN ]; then
    rm -f $FULLSCRN
fi

# Exit if no arguments given
test -z "$1" && test -z "$2" && usage

test -f $FSFILE && wtp $(cat $FSFILE)
if test -f $FSFILE && grep -q $1 $FSFILE; then
    rm -f $FSFILE
else
    printf '%s\n' "fullscreen" > $FULLSCRN
    wattr xywhi $1 > $FSFILE
    wtp 0 0 $SW $SH $1
    chwb -s 0 $1
fi

focus $1
