#!/bin/sh
#
# File        : /home/wildefyr/.fyre/fyrerc
# Maintainer  : Wildefyr | http://wildefyr.net
# Copyright   : Wildefyr | Licensed under the WTFPL license.
# Description : Use this file to set global variables for our script, meaning
# we only have to modify them in this file only.

# Global variables

ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)

PFW=$(pfw)
CUR=${2:-$(pfw)}
W=$(wattr w $CUR)
H=$(wattr h $CUR)

BW=${BW:-1}                    # border width
ACTIVE=${ACTIVE:-0xB52E2F}     # active border color
INACTIVE=${INACTIVE:-0x000000} # inactive border color

X=20
Y=30
TermW=462
TermH=260

XGAP=${XGAP:-$X}
IGAP=${IGAP:-10}
BGAP=${BGAP:-10}
TGAP=${TGAP:-$Y}

windowsOnscreen=$(lsw | wc -l)
maxHorizontalWindows=4

# Global Files
if [ ! -d /tmp/fyre ]; then
    mkdir /tmp/fyre/
fi

FSFILE=${FSFILE:-/tmp/fyre/fullinfo}
FULLSCRN=${FULLSCRN:-/tmp/fyre/fullscrn}
DETECT=${DETECT:-/tmp/fyre/detectList}
WLFILE=${WLFILE:-/tmp/fyre/windowList}
WLFILETEMP=${WLFILETEMP:-/tmp/fyre/windowTemp}
