#!/bin/sh
#
# File        : /home/wildefyr/.fyre/fyrerc
# Maintainer  : Wildefyr | http://wildefyr.net
# Copyright   : Wildefyr | Licensed under the WTFPL license.

# Global variables
ROOT=$(lsw -r)
SW=$(wattr w $ROOT)
SH=$(wattr h $ROOT)

PFW=$(pfw)
CUR=${2:-$(pfw)}
W=$(wattr w $CUR)
H=$(wattr h $CUR)

BW=${BW:-1}                    # border width
ACTIVE=${ACTIVE:-0x2E8B57}     # active border color
INACTIVE=${INACTIVE:-0x181818} # inactive border color

X=20
Y=20
TermW=462
TermH=260

XGAP=${XGAP:-$X}
IGAP=${IGAP:-10}
BGAP=${BGAP:-10}
TGAP=${TGAP:-$Y}

windowsOnscreen=$(lsw | wc -l)
maxHorizontalWindows=4

# Global Files
if [ ! -d /tmp/fyre/groups ]; then
    mkdir -p /tmp/fyre/groups
fi

GROUPSDIR=${GROUPSDIR:-/tmp/fyre/groups}

FSFILE=${FSFILE:-/tmp/fyre/fullinfo}
FULLSCRN=${FULLSCRN:-/tmp/fyre/fullscrn}
DETECT=${DETECT:-/tmp/fyre/detectList}
WLFILE=${WLFILE:-/tmp/fyre/windowList}
WLFILETEMP=${WLFILETEMP:-/tmp/fyre/windowTemp}
