#!/bin/sh

# File        : /home/wildefyr/.fyre/scripts/mouse
# Maintainer  : Wildefyr | http://wildefyr.net
# Copyright   : Wildefyr | Licensed under the WTFPL license.
# Depends on  : wmutils
# Description : Disable or Enable the mouse.
# See also    : focus, focus

case $1 in
    e)
        wmp 960 540
        xinput set-int-prop $(xinput | awk '/Mouse/ {printf "%s",$9}' | sed 's/id=//') "Device Enabled" 8 1
        ;;
    d)
        ROOT=$(lsw -r); SW=$(wattr w $ROOT); SH=$(wattr h $ROOT); wmp $SW $SH
        xinput set-int-prop $(xinput | awk '/Mouse/ {printf "%s",$9}' | sed 's/id=//') "Device Enabled" 8 0
        ;;
    *)
        echo "Usage: ./mouse [option]:

e | Enable Mouse
d | Disable Mouse"
esac
