#!/bin/sh
#
# wildefyr - 2016 (c) MIT
# launch a terminal with current path

. fyrerc

TERM="urxvtc"

class="$(class "$PFW" | tr '[A-Z]' '[a-z]')"

test "$class" = "$TERM" && {
    # find better method to retrieve path of current term
    CURPATH=$(wname $PFW | sed "s_~_${HOME}_")
    test -d "$CURPATH" && {
        $TERM -cd "$CURPATH" &
    }
}
