#!/bin/sh

# File            : /home/wildefyr/fyre/position
# Maintainer      : Wildefyr | http://wildefyr.net
# Copyright       : Wildefyr | Licensed under the WTFPL license.
# Depends On      : wmutils
# Original Author : z3bra

source fyrerc

case $2 in
    0x*)
        PFW=$2
        ;;
esac

case $1 in
    tr)
        X=$((SW - W - XGAP - BW*2))
        ;;
    bl)
        Y=$((SH - H - BGAP))
        ;;
    br)
        X=$((SW - W - XGAP - BW*2))
        Y=$((SH - H - BGAP))
        ;;
    md)
        X=$((SW/2 - W/2 - BW))
        Y=$((SH/2 - H/2 - BW))
        ;;
    mid)
        W=$((2*TermW)); H=$((2*TermH))
        X=$((SW/2 - W/2 - BW))
        Y=$((SH/2 - H/2 - BW))
        if [ $X -eq $(wattr x $PFW) ]; then
            exit
        fi
        ;;
    full)
        SW=$((SW - 2*XGAP - BW))
        SH=$((SH - TGAP - BGAP - BW))
        W=$SW; H=$SH
        ;;
    lft)
        SW=$((SW - 2*XGAP - BW))
        W=$((SW/2 - IGAP/2 - 1))
        H=$((SH - TGAP - BGAP - BW))
        ;;
    rht)
        SW=$((SW - 2*XGAP))
        W=$((SW/2 - IGAP/2 - BW))
        X=$((W + XGAP + IGAP + 2))
        H=$((SH - TGAP - BGAP - BW))
        ;;
    ext)
        X=$(wattr x $PFW)
        W=$TermW
        H=$((SH - TGAP - BGAP - BW))
        ;;
    res)
        X=$(wattr x $PFW); Y=$(wattr y $PFW)
        W=$TermW; H=$TermH
        ;;
esac

wtp $X $Y $W $H $PFW
