#!/bin/sh
#
# wildefyr - 2016 (c) MIT
# fyre initialisation and run loop

. fyrerc

# get monitor information
screens
# load our event watcher
eventually &
# reset group data
windows.sh -r

while true; do
    sleep "$DURATION"
done
