#!/bin/sh
#
# wildefyr - 2016 (c) MIT
# fyre initialisation

. fyrerc

# set background if WALL set
back

# reset group data on launch
windows --reset

# let the event watcher loop keep the X11 connection open
eventually
