#!/bin/sh
#
# wildefyr & z3bra - 2016 (c) wtfpl
# set or unset a border around a window

ARGS="$@"

usage() {
    cat << EOF
Usage: $(basename $0) [state] [wid]
EOF

    test $# -eq 0 || exit $1
}

main() {
    . fyrerc

    test "$#" -eq 0 && usage 1

    wid=$PFW

    case $2 in
        0x*) wid=$2 ;;
    esac

    case $1 in
        none)
            wattr "$wid" || printf '%s\n' "You have not entered a window id." >&2
            chwb -s 0 "$wid"
            ;;
        active)
            wattr "$wid" || printf '%s\n' "You have not entered a window id." >&2
            chwb -s "$BW" -c "$ACTIVE" "$wid"
            ;;
        warning)
            wattr "$wid" || printf '%s\n' "You have not entered a window id." >&2
            chwb -s "$BW" -c "$WARNING" "$wid"
            ;;
        inactive)
            chwb -s "$BW" -c "$INACTIVE" "$wid"
            ;;
        *) usage 0 ;;
    esac
}

main $ARGS
