#!/bin/sh
#
# wildefyr & z3bra - 2016 (c) MIT
# set border around a window

ARGS="$@"

usage() {
    cat >&2 << EOF
Usage: $(basename $0) [state] <wid>
EOF

    test $# -eq 0 || exit $1
}

main() {
    . fyrerc

    wattr "$2" && wid="$2" || wid="$PFW"

    case "$1" in
        "none")     chwb -s 0 "$wid"                  ;;
        "active")   chwb -s $BW -c "$ACTIVE" "$wid"   ;;
        "warning")  chwb -s $BW -c "$WARNING" "$wid"  ;;
        "inactive") chwb -s $BW -c "$INACTIVE" "$wid" ;;
        *)          usage 1                           ;;
    esac
}

test $# -eq 0 && usage 1

for arg in $ARGS; do
    case "$arg" in
        -q|--quiet)       QUIETFLAG=true ;;
        h|help|-h|--help) usage 0        ;;
    esac
done

test "$QUIETFLAG" = "true" && {
    main $ARGS 2>&1 > /dev/null
} || {
    main $ARGS
}
