#!/bin/sh
#
# wildefyr - 2016 (c) MIT
# sane resize in a direction

ARGS="$@"

usage() {
    cat >&2 << EOF
Usage: $(basename $0) <direction> <wid> <screen>
    -gr | --growright:  Grow current or given window right
    -gd | --growdown:   Grow current or given window down.
    -sl | --shrinkleft: Shrink current or given window left.
    -su | --shrinkup:   Shrink current or given window up.
    -h  | --help:       Show this help.
EOF

    test $# -eq 0 || exit $1
}

growDown() {
    test $H -lt $minH && {
        H=$minH
    } || {
        H=$((H + minH + VGAP + (VGAP / ROWS) * BW))
        eSH=$((eSH - (VGAP / ROWS) * BW))

        test $((Y + H - BGAP)) -gt $eSH && {
            Y=$((Y - minH - VGAP - (VGAP / ROWS) * BW))
        }
        test $H -ge $eSH && {
            Y=$TGAP
            H=$eSH
        }
    }
}

growRight() {
    test $W -lt $minW && {
        W=$minW
    } || {
        W=$((W + minW + IGAP + (IGAP / COLS) * BW))
        eSW=$((eSW - (IGAP / COLS) * BW))

        test $((X + W - XGAP)) -gt $eSW && {
            X=$((X - minW - IGAP - (IGAP / COLS) * BW))
        }
        test $W -ge $eSW && {
            X=$XGAP
            W=$eSW
        }
    }
}

shrinkUp() {
    test $H -le $minH && {
        test $H -lt 20 && exit 0
        H=$((H/2 - VGAP/2))
    } || {
        H=$((H - minH - VGAP - (VGAP / ROWS) * BW))
    }
}

shrinkLeft() {
    test $W -le $minW && {
        test $W -lt 20 && exit 0
        W=$((W/2 - VGAP/2))
    } || {
        W=$((W - minW - IGAP - (IGAP / COLS) * BW))
    }
}

moveMouse() {
    . mouse

    mouseStatus=$(getMouseStatus)
    test ! -z $mouseStatus && test $mouseStatus -eq 1 && moveMouseEnabled "$wid"
}

main() {
    . fyrerc

    wattr "$2" && wid="$2" || wid="$PFW"
    # exit if wid is currently fullscreen
    grep -qw "$wid" "$FSFILE" 2> /dev/null && return 1

    case "$1" in
        -gd|--growdown)   growDown   ;;
        -su|--shrinkup)   shrinkUp   ;;
        -gr|--growright)  growRight  ;;
        -sl|--shrinkleft) shrinkLeft ;;
        *)                usage 1    ;;
    esac

    wtp $X $Y $W $H "$wid"
    test "$MOUSE" = "true" && moveMouse
}

test $# -eq 0 && usage 1

for arg in $ARGS; do
    case "$arg" in
        -q|--quiet)       QUIETFLAG=true ;;
        h|help|-h|--help) usage 0        ;;
    esac
done

test "$QUIETFLAG" = "true" && {
    main $ARGS 2>&1 > /dev/null
} || {
    main $ARGS
}
