#!/bin/sh
#
# File       : /home/wildefyr/fyre/toggleStack
# Maintainer : Wildefyr | http://wildefyr.net

source fyrerc

case $1 in
    0x*)
        CUR=$1
        ;;
    *)
        CUR=$PFW
esac

if test -f $TOPWID && grep -q $CUR $TOPWID; then
    rm -f $TOPWID
else
    echo $CUR > $TOPWID
fi
