#!/bin/sh
#
# File        : /home/wildefyr/.fyre/scripts/winkill
# Maintainer  : Wildefyr | http://wildefyr.net
# Copyright   : Wildefyr | Licensed under the WTFPL license.
# Description : Perform checks and tasks when killing a window.

wid=$1
windowC=$(wclass c $wid)
windowP=$(wclass p $wid)

if [[ $(wclass c $(pfw)) == "urxvtc" ]]; then
    killwa $PFW
    tile
else
    sed -i "/$PFW/d" $DETECT
    checkFullscreen
fi

killw $(pfw); bgc
