#!/bin/sh
#
# File            : /home/wildefyr/fyre/yawee
# Maintainer      : Wildefyr | http://wildefyr.net
# Copyright       : Wildefyr | Licensed under the WTFPL license.
# Depends on      : wew; wmutils
# Original Author : z3bra
# Description     : Read window events and execute processes.

source fyrerc

while IFS=: read ev wid; do
    case $ev in
        # entering window
        7)
            if ! wattr o $wid; then
                focus $wid
            fi
            ;;
        # window creation
        16)
            if ! wattr o $wid; then
                position tl $wid
                if [ ! -e $FULLSCRN ]; then
                    tile
                fi
            fi
            ;;
        # window unmap
        18)
            wattr $(pfw) || focus prev 2>/dev/null

            # Don't tile when window is still in unmarked list.
            for i in $(seq $(lsw -u | wc -l)); do
                current=$(lsw -u | head -n $i | tail -1)
                if [[ $wid == $current ]]; then
                    if [[ $(wclass c $wid) == "urxvtc" ]]; then
                        tileFlag=0
                        break
                    fi
                    tileFlag=1
                    break
                else
                    tileFlag=0
                fi
            done

            if [ $tileFlag -eq 0 ]; then
                tile
            fi
            ;;
        # mapping requests
        19)
            if ! wattr o $wid; then
                chwb -s 1 -c $INACTIVE $wid
                focus $wid
            fi
            ;;
    esac
done
