#!/bin/sh
#
# File            : /home/wildefyr/fyre/yawee
# Maintainer      : Wildefyr | http://wildefyr.net
# Copyright       : Wildefyr | Licensed under the WTFPL license.
# Depends on      : wew; wmutils
# Original Author : z3bra
# Description     : Read window events and execute processes.

source fyrerc

chwsoTop() {
    cur=$(cat $TOPWID)
    chwso -r $cur
}

while IFS=: read ev wid; do
    case $ev in

        # entering window
        7)
            if ! wattr o $wid; then
                focus $wid
                chwsoTop
            fi
            ;;

        # window creation
        16)
            if ! wattr o $wid; then
                position tl $wid
                #setborder active $(pfw)
                chwsoTop
            fi
            ;;

        # window unmap
        18)
            chwsoTop
            wattr $(pfw) || focus prev 2>/dev/null

            # Don't tile when window is in unmarked list.
            for i in $(seq $(lsw -u | wc -l)); do
                current=$(lsw -u | head -n $i | tail -1)
                if [[ $wid == $current ]]; then
                    if [[ $(wclass c $wid) == "urxvtc" ]]; then
                        tileFlag=1
                        break
                    else
                        tileFlag=0
                    fi
                else
                    tileFlag=1
                fi
            done

            if [ $tileFlag = 1 ]; then
                tile
            fi
            ;;

        # mapping requests
        19)
            chwsoTop
            if ! wattr o $wid; then
                setborder inactive $wid
                focus $wid
            fi
            ;;

    esac
done
