#!/bin/sh
#
# File            : /home/wildefyr/fyre/yawee
# Maintainer      : Wildefyr | http://wildefyr.net
# Copyright       : Wildefyr | Licensed under the WTFPL license.
# Depends on      : wew; wmutils
# Original Author : z3bra
# Description     : Read window events and execute processes.

source fyrerc

while IFS=: read ev wid; do
    case $ev in

        4)
            if ! wattr o $wid; then
                focus $wid
            fi
            ;;

        16)
            if ! wattr o $wid; then
                if [[ $(wclass p $wid) == *"vol"* ]]; then
                    position md $wid
                elif [[ $(wclass p $wid) == *"sshserver"* ]]; then
                    position mid $wid
                    wgroups -s 3
                else
                    position tl $wid
                fi
                tile
            fi
            ;;

        18)
            wattr $(pfw) || focus prev 2>/dev/null

            # To avoid using wew event 17
            for current in $(lsw -u); do
                if [[ $wid == $current ]]; then
                    if [[ $(wclass c $wid) == "urxvtc" ]]; then
                        tileFlag=1
                        break
                    else
                        tileFlag=0
                    fi
                else
                    tileFlag=1
                fi
            done

            if [ $tileFlag -eq 1 ]; then
                tile
            fi
            ;;

        19)
            if ! wattr o $wid; then
                setborder inactive $wid
                focus $wid
            fi
            ;;

    esac
done
